# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='teamid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
